### ISSUE TITLE
Question: Which history type is used for react-router

### ISSUE THREAD

**Issue by thuringia** [sinnerschrader/aem-react-js#11]
Hi everyone,

I could not find out which type of history is used for routing in neither the aem-react-js nor the aem-react repo. If a browserHistory is used it would be very interesting to know how AEM is configured to handle things like multi-screen apps that do not necessarily have corresponding content pages.

Any help is greatly appreciated.
Thanks and keep up the great work!

**Comment by stemey** [comment]
Hi thuringia,

in the demo app the client uses a [browser history](https://github.com/sinnerschrader/aem-react/blob/master/demo/src/main/ts/client.tsx#L20) and the server uses the [memory history](https://github.com/sinnerschrader/aem-react/blob/master/demo/src/main/ts/server.tsx#L28)  since the server's url does not change.

Currently I have only investigated the idea of each app screen related to a content page. The [ResourceRoute](https://github.com/sinnerschrader/aem-react-js/blob/master/router/ResourceRoute.tsx) translates the router's path and params into a url and then appends a static relative path to the resource inside the page. So probably you cannot use the ResourceRoute as it is. 

I will get to work on writing more documentation (SPA, architecture, ..) soon.

I am really interested in your findings.
Stefan

**Comment by stemey** [comment]
added more docs on router

**Comment by gregorskii** [comment]
Can you explain the router a bit more?

**How is the Resource Mapper working, what is its purpose?**

**Do you need to have dedicated CQ content pages for each route the router would link to?**

**How does the router work when in author mode versus production?**

**What is the relationship between `indexPath` `pattern` and `resourcePath` in the example?**

What would be the correct config to get a page say `content/APPNAME/test.html` to support sub pages via browser history?

When I try to set this up the path:

http://localhost:4502/content/APPNAME/test.html?wcmmode=disabled

Works fine.

But when I try to do:

http://localhost:4502/content/APPNAME/test.html/new-route?wcmmode=disabled

The values for indexPath etc get messed up:

```
indexPath: "/content/APPNAME/test.html/new.html"
pattern: "/content/APPNAME/test.html/new(:name).html"
resourcePath: "/content/APPNAME/test.html/new"
```

And the router stops working.

**What is the purpose of the "AemRoute"?**

I believe this is a wrapped version of the standard Link which provides the things needed for the ResourceComponent?

**What is the purpose of the "AemLink"?**

It looks like this supports keeping track of the wcmmode disabled property and other things.

I am seeing a couple other issues:

When I include the `AemLink` class in any component I get a crash where React thinks an empty component is trying to be rendered.

```
import React from 'react';
import AemComponent from 'aem-react-js/component/AemComponent';
import { Link } from 'react-router';
import { AemLink } from 'aem-react-js/router/AemLink';

import Heading from 'builder/components/heading';

class Test extends AemComponent {
  render() {
    return (
      <section>
        <Heading text="Test Landing" />
        <AemLink to="/newroute">Link</AemLink>
      </section>
    );
  }
}

export default Test;
```

Error:

```
Caused by: javax.script.ScriptException: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. in <eval> at line number 310 at column number 4
```

Looks like the AEM "LinkChecker" is getting in the way of the router working:

https://helpx.adobe.com/experience-manager/kb/DisableLinkChecker.html

I am trying to disable it.

**Comment by gregorskii** [comment]
Disabled the link checker. I am using React Router Links and having some luck, except AEM kicks in and renders no content when the http://localhost:4502/content/APPNAME/test.html/new-route page is rendered. On Express SPA's one would just tell express to fallback to the history API, is there an equivalent in AEM?

**Comment by gregorskii** [comment]
I think this is related to the resourceMapper not creating the correct resourcePath, indexPath, and pattern. I am investigating.

AEM does support requestMapping nodes which can redirect pages back to the root of the SPA.

Looking into both of these.

**Comment by stemey** [comment]
AemRoute
the AemRoute converts a routing url to a resourcePath and passes it to a ResourceComponent. Using AemRoute is important to be able to load route's lazily via ajax. Basically the ResourceComponent is rendered on the server and its state is sent to the client and merged with the existing cache.

AemLink
acts as a normal link in author mode and uses the router history otherwise. You can disable link checking via attributes but you shouldn't have to because in author mode the links must be valid.

ResourceMapper

it is the equivalent of ResourceResolver which maps between urls and resourcePaths. This should usually be implemented in publisher to map from /content/<site> to / or something similar.

**Comment by stemey** [comment]
closed due to inactivity
